GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhcnlhIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcxNjM1MDc4NiwiZXhwIjoxNzE2MzUwODA2fQ.s5sbEl3xt6v5gEBWBSog_sfUnj8z39QikKca4s3rxHY

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "test1",
    "email": "test1@gmail.com",
    "password": "12345",
    "confirmPassword": "12345"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout

###
POST http://localhost:4000/sumateraselatan
Content-Type: application/json

{
    "restaurant_name": "The Eight Hour Gold",
    "description": "Kue Delapan Jam adalah kue tradisional khas Sumatera Selatan, Indonesia. Kue ini terkenal karena proses pembuatannya yang memakan waktu yang cukup lama, hingga delapan jam, untuk menghasilkan tekstur yang lembut dan aroma yang kaya. Kue Delapan Jam terbuat dari bahan-bahan dasar seperti tepung terigu, gula, telur, santan, dan mentega atau margarin. Proses pembuatannya dimulai dengan mencampurkan semua bahan, kemudian adonan tersebut dikukus dalam loyang yang telah diolesi mentega atau margarin hingga matang.",
    "google_maps_link": "https://maps.app.goo.gl/NCmJUf4chUW12nJH7",
    "rating": 4.9
}

###
GET http://localhost:4000/lampung

###
DELETE http://localhost:4000/jambi/1

###
POST http://localhost:4000/aceh
Content-Type: application/json