GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhcnlhIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcxNjIwODc1MiwiZXhwIjoxNzE2MjA4NzcyfQ.m91Rr-HBJa83_TRs8F6q9VqOde0TuPlwsxwv792GFos

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "test1",
    "email": "test1@gmail.com",
    "password": "12345",
    "confirmPassword": "12345"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout

###
POST http://localhost:4000/lampung
Content-Type: application/json

{
    "name": "Seruit",
    "description": "Hidangan ini berupa ikan goreng atau bakar yang dicampur sambal terasi dan tempoyak (olahan durian). Istilah yang dipakai untuk merujuk makan seruit adalah 'nyeruit'. Nyeruit berarti makan bersama keluarga maupun masyarakat dengan hidangannya berupa seruit.",
    "restaurant_name": "Temphoyac",
    "google_maps_link": "https://maps.app.goo.gl/rMR8Lz5prfTzH9rC8",
    "rating": 4.5
}

###
GET http://localhost:4000/lampung

###
DELETE http://localhost:4000/jambi/1

###
POST http://localhost:4000/aceh
Content-Type: application/json