GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhcnlhIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTcxNjM1MDc4NiwiZXhwIjoxNzE2MzUwODA2fQ.s5sbEl3xt6v5gEBWBSog_sfUnj8z39QikKca4s3rxHY

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "1234",
    "confirmPassword": "1234"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}

###
GET http://localhost:4000/token

###
DELETE http://localhost:4000/logout

###
POST http://localhost:4000/sulawesiselatan
Content-Type: application/json

{
    "restaurant_name": "Pallubasa Serigala",
    "description": "Sup daging sapi dengan kuah kental yang disajikan dengan kelapa parut sangrai.",
    "google_maps_link": "https://maps.app.goo.gl/ywsMHQnoqHzbNxxo7",
    "rating": 4.6
}

###
GET http://localhost:4000/lampung

###
DELETE http://localhost:4000/jambi/1

###
POST http://localhost:4000/aceh
Content-Type: application/json